/* tests/test-adif.vala
 *
 * Copyright 2026 Jay Baird (K0VCZ)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

using Artemis.Adif;

private void test_adif_parse_header_and_records () {
    string input =
        "Generated by Artemis\n" +
        "<adif_ver:5>3.1.7<programid:7>Artemis<eoh>\n" +
        "<call:5>K1ABC<qso_date:8>20260517<time_on:6>194500<eor>\n" +
        "<call:4>W1AW<mode:2:C>CW<eor>";

    Document document;
    try {
        document = Parser.from_string (input);
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }

    assert (document.header.text == "Generated by Artemis\n");
    assert (document.header.get ("ADIF_VER") == "3.1.7");
    assert (document.header.get ("PROGRAMID") == "Artemis");
    assert (document.records.size == 2);
    assert (document.records[0].get ("CALL") == "K1ABC");
    assert (document.records[0].get ("QSO_DATE") == "20260517");
    assert (document.records[0].get ("TIME_ON") == "194500");
    assert (document.records[1].get_field ("MODE").type_indicator == "C");
    assert (document.records[1].get ("MODE") == "CW");
}

private void test_adif_generate_round_trip () {
    var document = new Document ();
    document.header.text = "Generated by Artemis\n";
    try {
        document.header.set ("ADIF_VER", "3.1.7");
        document.header.set ("PROGRAMID", "Artemis");
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }

    var first = new Record ();
    try {
        first.set ("CALL", "K0VCZ");
        first.set ("BAND", "20M");
        first.set ("MODE", "SSB");
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }
    document.records.add (first);

    var second = new Record ();
    try {
        second.set ("CALL", "W1AW");
        second.set ("TIME_ON", "194500", "T");
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }
    document.records.add (second);

    string output;
    Document reparsed;
    try {
        output = Generator.to_string (document);
        reparsed = Parser.from_string (output);
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }

    assert (reparsed.header.get ("PROGRAMID") == "Artemis");
    assert (reparsed.records.size == 2);
    assert (reparsed.records[0].get ("CALL") == "K0VCZ");
    assert (reparsed.records[0].get ("BAND") == "20M");
    assert (reparsed.records[1].get_field ("TIME_ON").type_indicator == "T");
    assert (reparsed.records[1].get ("TIME_ON") == "194500");
}

private void test_adif_reject_duplicate_record_field () {
    string input = "<call:5>K1ABC<CALL:4>W1AW<EOR>";

    try {
        Parser.from_string (input);
        assert_not_reached ();
    } catch (Artemis.Adif.Error error) {
        assert (error is Artemis.Adif.Error.INVALID_FORMAT);
    }
}

private void test_adif_parse_empty_header_marker () {
    string input = "<eoh><call:5>K1ABC<qso_date:8>20260517<time_on:6>225054<eor>";

    Document document;
    try {
        document = Parser.from_string (input);
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }

    assert (document.records.size == 1);
    assert (document.records[0].get ("CALL") == "K1ABC");
    assert (document.records[0].get ("TIME_ON") == "225054");
}

private void test_adif_parse_record_without_header () {
    string input = "<call:5>K1ABC<qso_date:8>20260517<time_on:6>225054<eor>";

    Document document;
    try {
        document = Parser.from_string (input);
    } catch (Artemis.Adif.Error error) {
        assert_not_reached ();
    }

    assert (document.header.fields.size == 0);
    assert (document.records.size == 1);
    assert (document.records[0].get ("CALL") == "K1ABC");
}

private void test_adif_parse_qso_datetime_utc () {
    var with_seconds = parse_qso_datetime_utc ("20260517", "194500");
    assert (with_seconds != null);
    assert (with_seconds.to_utc ().format ("%Y%m%d%H%M%S") == "20260517194500");

    var without_seconds = parse_qso_datetime_utc ("20260517", "1945");
    assert (without_seconds != null);
    assert (without_seconds.to_utc ().format ("%Y%m%d%H%M%S") == "20260517194500");
}

private void test_adif_reject_invalid_qso_datetime () {
    assert (parse_qso_datetime_utc ("2026051", "194500") == null);
    assert (parse_qso_datetime_utc ("20260517", "194") == null);
    assert (parse_qso_datetime_utc ("20260517", "19A500") == null);
    assert (parse_qso_datetime_utc ("2026AA17", "194500") == null);
}

public int main (string[] args) {
    Test.init (ref args);

    Test.add_func ("/adif/parse-header-and-records", test_adif_parse_header_and_records);
    Test.add_func ("/adif/generate-round-trip", test_adif_generate_round_trip);
    Test.add_func ("/adif/reject-duplicate-record-field", test_adif_reject_duplicate_record_field);
    Test.add_func ("/adif/parse-empty-header-marker", test_adif_parse_empty_header_marker);
    Test.add_func ("/adif/parse-record-without-header", test_adif_parse_record_without_header);
    Test.add_func ("/adif/parse-qso-datetime-utc", test_adif_parse_qso_datetime_utc);
    Test.add_func ("/adif/reject-invalid-qso-datetime", test_adif_reject_invalid_qso_datetime);

    return Test.run ();
}
