on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: CI
jobs:
  lint:
    name: "Vala Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: elementary/actions/vala-lint@master
      with:
        conf: vala-lint.conf
  prepare-subprojects:
    runs-on: ubuntu-latest
    outputs:
      subprojects-artifact: subprojects
    steps:
      - uses: actions/checkout@v4

      - name: Ensure meson
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip ninja-build
          pip3 install meson==1.8.2

      - name: Download meson subprojects (host)
        run: meson subprojects download

      - name: Upload subprojects artifact
        uses: actions/upload-artifact@v4
        with:
          name: subprojects
          path: subprojects
  flatpak-builder:
    name: "Flatpak Builder"
    needs: [ lint, prepare-subprojects ]
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.variant.runner }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with: 
        name: subprojects
        path: ./subprojects
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: "com.k0vcz.artemis.Devel.flatpak"
        run-tests: true
        manifest-path: "com.k0vcz.Artemis.json"
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.variant.arch }}
        repository-name: flathub
        repository-url: https://dl.flathub.org/repo/flathub.flatpakrepo